[package]
name = "iron-insights-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"

[dependencies.web-sys]
version = "0.3.77"
features = [
  "console",
]