// share_card.rs - SVG Share Card Generator for beautiful social media cards
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct ShareCardData {
    pub name: String,
    pub bodyweight: f32,
    pub squat: Option<f32>,
    pub bench: Option<f32>,
    pub deadlift: Option<f32>,
    pub total: Option<f32>,
    pub dots_score: Option<f32>,
    pub strength_level: String,
    pub percentile: Option<f32>,
    pub lift_type: String,
    pub sex: String,
}

pub enum CardTheme {
    Default,
    Dark,
    Minimal,
    Powerlifting,
}

pub fn generate_themed_share_card_svg(data: &ShareCardData, theme: CardTheme) -> String {
    match theme {
        CardTheme::Default => generate_default_card(data),
        CardTheme::Dark => generate_dark_card(data),
        CardTheme::Minimal => generate_minimal_card(data),
        CardTheme::Powerlifting => generate_powerlifting_card(data),
    }
}

fn generate_default_card(data: &ShareCardData) -> String {
    let card_width = 800;
    let card_height = 600;
    
    // Colors as string constants to avoid parsing issues
    let bg_start = "#667eea";
    let bg_end = "#764ba2";
    let accent = "#4facfe";

    let main_lift_value = match data.lift_type.as_str() {
        "squat" => data.squat,
        "bench" => data.bench, 
        "deadlift" => data.deadlift,
        "total" => data.total,
        _ => data.squat,
    };

    let main_lift_display = main_lift_value
        .map(|v| format!("{:.0} kg", v))
        .unwrap_or_else(|| "-".to_string());

    let dots_display = data.dots_score
        .map(|d| format!("{:.1}", d))
        .unwrap_or_else(|| "-".to_string());

    let percentile_display = data.percentile
        .map(|p| format!("{:.0}%", p))
        .unwrap_or_else(|| "-".to_string());

    let lift_emoji = match data.lift_type.as_str() {
        "squat" => "🏋️",
        "bench" => "💪", 
        "deadlift" => "⬆️",
        "total" => "🏆",
        _ => "🏋️",
    };

    format!(
        r##"<svg width="{}" height="{}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:{};stop-opacity:1" />
      <stop offset="100%" style="stop-color:{};stop-opacity:1" />
    </linearGradient>
    <filter id="shadow">
      <feDropShadow dx="0" dy="4" stdDeviation="8" flood-opacity="0.3"/>
    </filter>
  </defs>
  
  <rect width="100%" height="100%" fill="url(#bg)" rx="20"/>
  <rect x="0" y="0" width="100%" height="80" fill="{}" rx="20"/>
  
  <text x="40" y="50" font-family="Arial" font-size="32" font-weight="bold" fill="white">
    🏋️ Iron Insights
  </text>
  
  <rect x="40" y="140" width="720" height="420" fill="white" rx="15" filter="url(#shadow)" opacity="0.95"/>
  
  <text x="400" y="190" font-family="Arial" font-size="36" font-weight="bold" text-anchor="middle" fill="#333">
    {}
  </text>
  
  <g transform="translate(100, 240)">
    <rect x="0" y="0" width="150" height="100" fill="{}" rx="10" opacity="0.2"/>
    <text x="75" y="30" font-family="Arial" font-size="14" text-anchor="middle" fill="#666">
      {} {}
    </text>
    <text x="75" y="60" font-family="Arial" font-size="28" text-anchor="middle" fill="#333" font-weight="bold">
      {}
    </text>
    
    <rect x="170" y="0" width="150" height="100" fill="{}" rx="10" opacity="0.2"/>
    <text x="245" y="30" font-family="Arial" font-size="14" text-anchor="middle" fill="#666">
      DOTS Score
    </text>
    <text x="245" y="60" font-family="Arial" font-size="28" text-anchor="middle" fill="#333" font-weight="bold">
      {}
    </text>
    
    <rect x="340" y="0" width="150" height="100" fill="{}" rx="10" opacity="0.2"/>
    <text x="415" y="30" font-family="Arial" font-size="14" text-anchor="middle" fill="#666">
      Level
    </text>
    <text x="415" y="60" font-family="Arial" font-size="20" text-anchor="middle" fill="#333" font-weight="bold">
      {}
    </text>
  </g>
  
  <g transform="translate(100, 380)">
    <text x="0" y="20" font-family="Arial" font-size="14" fill="#666">
      Bodyweight: {:.1}kg | Percentile: {} | Category: {}
    </text>
    <text x="0" y="50" font-family="Arial" font-size="12" fill="#999">
      Generated by Iron Insights - Powerlifting Analytics
    </text>
  </g>
  
</svg>"##,
        card_width, card_height, bg_start, bg_end, accent,
        data.name, accent, lift_emoji, data.lift_type.to_uppercase(), main_lift_display,
        accent, dots_display, accent, data.strength_level,
        data.bodyweight, percentile_display, data.sex
    )
}

fn generate_dark_card(data: &ShareCardData) -> String {
    let card_width = 800;
    let card_height = 600;

    let main_lift_value = match data.lift_type.as_str() {
        "squat" => data.squat,
        "bench" => data.bench, 
        "deadlift" => data.deadlift,
        "total" => data.total,
        _ => data.squat,
    };

    let main_lift_display = main_lift_value
        .map(|v| format!("{:.0} kg", v))
        .unwrap_or_else(|| "-".to_string());

    let dots_display = data.dots_score
        .map(|d| format!("{:.1}", d))
        .unwrap_or_else(|| "-".to_string());

    let lift_emoji = match data.lift_type.as_str() {
        "squat" => "🏋️",
        "bench" => "💪", 
        "deadlift" => "⬆️",
        "total" => "🏆",
        _ => "🏋️",
    };

    format!(
        r##"<svg width="{}" height="{}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="darkBg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#1a1a2e;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#16213e;stop-opacity:1" />
    </linearGradient>
  </defs>
  
  <rect width="100%" height="100%" fill="url(#darkBg)" rx="20"/>
  <rect x="0" y="0" width="100%" height="80" fill="#0f3460" rx="20"/>
  
  <text x="40" y="50" font-family="Arial" font-size="32" font-weight="bold" fill="#00d2ff">
    🏋️ Iron Insights
  </text>
  
  <rect x="40" y="140" width="720" height="420" fill="#0f0e17" rx="15" opacity="0.9"/>
  
  <text x="400" y="190" font-family="Arial" font-size="36" font-weight="bold" text-anchor="middle" fill="white">
    {}
  </text>
  
  <g transform="translate(100, 240)">
    <rect x="0" y="0" width="150" height="100" fill="#e94560" rx="10" opacity="0.3"/>
    <text x="75" y="30" font-family="Arial" font-size="14" text-anchor="middle" fill="#a7a9be">
      {} {}
    </text>
    <text x="75" y="60" font-family="Arial" font-size="28" text-anchor="middle" fill="white" font-weight="bold">
      {}
    </text>
    
    <rect x="170" y="0" width="150" height="100" fill="#00d2ff" rx="10" opacity="0.3"/>
    <text x="245" y="30" font-family="Arial" font-size="14" text-anchor="middle" fill="#a7a9be">
      DOTS Score
    </text>
    <text x="245" y="60" font-family="Arial" font-size="28" text-anchor="middle" fill="white" font-weight="bold">
      {}
    </text>
    
    <rect x="340" y="0" width="150" height="100" fill="#f25f4c" rx="10" opacity="0.3"/>
    <text x="415" y="30" font-family="Arial" font-size="14" text-anchor="middle" fill="#a7a9be">
      Level
    </text>
    <text x="415" y="60" font-family="Arial" font-size="20" text-anchor="middle" fill="white" font-weight="bold">
      {}
    </text>
  </g>
  
  <text x="400" y="500" font-family="Arial" font-size="14" text-anchor="middle" fill="#a7a9be">
    {:.1}kg • {} • {} • Generated by Iron Insights
  </text>
  
</svg>"##,
        card_width, card_height,
        data.name,
        lift_emoji, data.lift_type.to_uppercase(), main_lift_display,
        dots_display,
        data.strength_level,
        data.bodyweight, data.percentile.map(|p| format!("{:.0}%", p)).unwrap_or_else(|| "-".to_string()), data.sex
    )
}

fn generate_minimal_card(data: &ShareCardData) -> String {
    let card_width = 800;
    let card_height = 400;

    let main_lift_value = match data.lift_type.as_str() {
        "squat" => data.squat,
        "bench" => data.bench, 
        "deadlift" => data.deadlift,
        "total" => data.total,
        _ => data.squat,
    };

    let main_lift_display = main_lift_value
        .map(|v| format!("{:.0} kg", v))
        .unwrap_or_else(|| "-".to_string());

    let dots_display = data.dots_score
        .map(|d| format!("{:.1}", d))
        .unwrap_or_else(|| "-".to_string());

    format!(
        r##"<svg width="{}" height="{}" xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="white" rx="8"/>
  <rect width="100%" height="100%" fill="none" stroke="#e5e5e5" stroke-width="2" rx="8"/>
  
  <line x1="60" y1="60" x2="740" y2="60" stroke="#333" stroke-width="2"/>
  
  <text x="60" y="40" font-family="Arial" font-size="18" fill="#666">
    Iron Insights
  </text>
  
  <text x="400" y="120" font-family="Arial" font-size="42" font-weight="bold" text-anchor="middle" fill="#333">
    {}
  </text>
  
  <g transform="translate(100, 180)">
    <text x="0" y="0" font-family="Arial" font-size="14" fill="#666">
      {}
    </text>
    <text x="0" y="30" font-family="Arial" font-size="48" fill="#333">
      {}
    </text>
    
    <text x="250" y="0" font-family="Arial" font-size="14" fill="#666">
      DOTS SCORE
    </text>
    <text x="250" y="30" font-family="Arial" font-size="48" fill="#333">
      {}
    </text>
    
    <text x="500" y="0" font-family="Arial" font-size="14" fill="#666">
      STRENGTH LEVEL
    </text>
    <text x="500" y="30" font-family="Arial" font-size="28" fill="#333" font-weight="bold">
      {}
    </text>
  </g>
  
  <text x="60" y="350" font-family="Arial" font-size="12" fill="#999">
    Generated by Iron Insights • Powerlifting Analytics
  </text>
  
</svg>"##,
        card_width, card_height,
        data.name,
        data.lift_type.to_uppercase(),
        main_lift_display,
        dots_display,
        data.strength_level,
    )
}

fn generate_powerlifting_card(data: &ShareCardData) -> String {
    let card_width = 800;
    let card_height = 600;

    let squat_display = data.squat.map(|v| format!("{:.0}", v)).unwrap_or_else(|| "-".to_string());
    let bench_display = data.bench.map(|v| format!("{:.0}", v)).unwrap_or_else(|| "-".to_string());
    let deadlift_display = data.deadlift.map(|v| format!("{:.0}", v)).unwrap_or_else(|| "-".to_string());
    let total_display = data.total.map(|v| format!("{:.0}", v)).unwrap_or_else(|| "-".to_string());
    let dots_display = data.dots_score.map(|d| format!("{:.1}", d)).unwrap_or_else(|| "-".to_string());

    format!(
        r##"<svg width="{}" height="{}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="powerliftingBg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#2c1810;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#8b4513;stop-opacity:1" />
    </linearGradient>
  </defs>
  
  <rect width="100%" height="100%" fill="url(#powerliftingBg)" rx="15"/>
  <rect x="0" y="0" width="100%" height="100" fill="#d2691e" rx="15"/>
  
  <text x="50" y="55" font-family="Arial" font-size="36" font-weight="bold" fill="white">
    🏋️ POWERLIFTING MEET CARD
  </text>
  
  <text x="400" y="150" font-family="Arial" font-size="42" font-weight="bold" text-anchor="middle" fill="#fffaf0">
    {}
  </text>
  
  <rect x="50" y="180" width="700" height="360" fill="#fffaf0" rx="10" opacity="0.95"/>
  
  <g transform="translate(80, 220)">
    <rect x="0" y="0" width="640" height="40" fill="#8b4513"/>
    <text x="80" y="25" font-family="Arial" font-size="16" font-weight="bold" text-anchor="middle" fill="white">SQUAT</text>
    <text x="240" y="25" font-family="Arial" font-size="16" font-weight="bold" text-anchor="middle" fill="white">BENCH</text>
    <text x="400" y="25" font-family="Arial" font-size="16" font-weight="bold" text-anchor="middle" fill="white">DEADLIFT</text>
    <text x="560" y="25" font-family="Arial" font-size="16" font-weight="bold" text-anchor="middle" fill="white">TOTAL</text>
    
    <rect x="0" y="40" width="640" height="60" fill="#f5deb3" stroke="#8b4513"/>
    <text x="80" y="75" font-family="Arial" font-size="28" font-weight="bold" text-anchor="middle" fill="#2c1810">{}</text>
    <text x="240" y="75" font-family="Arial" font-size="28" font-weight="bold" text-anchor="middle" fill="#2c1810">{}</text>
    <text x="400" y="75" font-family="Arial" font-size="28" font-weight="bold" text-anchor="middle" fill="#2c1810">{}</text>
    <text x="560" y="75" font-family="Arial" font-size="28" font-weight="bold" text-anchor="middle" fill="#2c1810">{}</text>
    
    <rect x="0" y="120" width="640" height="80" fill="#2c1810"/>
    <text x="320" y="145" font-family="Arial" font-size="18" font-weight="bold" text-anchor="middle" fill="#d2691e">
      DOTS SCORE
    </text>
    <text x="320" y="185" font-family="Arial" font-size="48" font-weight="bold" text-anchor="middle" fill="#fffaf0">
      {}
    </text>
    
    <rect x="0" y="220" width="640" height="60" fill="#d2691e"/>
    <text x="320" y="240" font-family="Arial" font-size="16" font-weight="bold" text-anchor="middle" fill="white">
      STRENGTH CLASSIFICATION
    </text>
    <text x="320" y="265" font-family="Arial" font-size="32" font-weight="bold" text-anchor="middle" fill="white">
      {}
    </text>
  </g>
  
  <text x="400" y="575" font-family="Arial" font-size="14" text-anchor="middle" fill="#fffaf0" opacity="0.8">
    Generated by Iron Insights • Bodyweight: {:.1}kg • {}-Class
  </text>
</svg>"##,
        card_width, card_height,
        data.name,
        squat_display, bench_display, deadlift_display, total_display,
        dots_display,
        data.strength_level,
        data.bodyweight, data.sex,
    )
}